### PR TITLE
[feat] Typography

### PR DESCRIPTION
**Pull request by Ronak-Mutha**
# Text Utilities
- headings
image

- small text, gray text, and center text
image

### CODE REVIEW

**Review by MaruthiPothuganti — COMMENTED** [review]
The code is clean and made good use of the utility classes

**Review by abhij1607 — APPROVED** [review]
A suggestion to define and use variables instead of hardcoded values
Other than that very clean code and can be merged

**Comment by Ronak-Mutha** [comment]
> A suggestion to define and use variables instead of hardcoded values Other than that very clean code and can be merged

Yes Abhi, but in this case as I'm using this as a base file and as it will be on atomic level, I think for now I'll keep it as is. Later on, when I'm fixed on some set of values then I'll do as suggested.

**Comment by Ronak-Mutha** [comment]
Got 2 reviews. Merging to dev branch and closing this branch.

**Pull request merged**
