### PR TITLE
[feat] Avatar

### PR DESCRIPTION
**Pull request by Ronak-Mutha**
# Avatar
- Added four sizes of avatar xs, sm, md, and lg.

image

### CODE REVIEW

**Review by stutisk — APPROVED** [review]
It looks good to merge

**Review by GuptaEesh — COMMENTED** [review]
Code looks clean and good to merge.

**Review by stutisk — APPROVED** [review]
Can go forward with merging

**Comment by Ronak-Mutha** [comment]
Got 2 reviews. Merging to dev and closing this branch

**Pull request merged**
